### ISSUE TITLE
How do I scroll through the page when my content exceeds the page size in BMView

### ISSUE THREAD

**Issue by qq759979949** [ptc-iot-sharing/BMCoreUIWidgets#21]
Hi,thanks for the widget first,i have some questions when i use the BMview widget.
How do I scroll the page when I have more content than the size of the page, and now I have a situation where the content is not complete, and I can't scroll the page.

**Comment by BogdanMihaiciuc** [comment]
The basic view widget doesn't do scrolling at all. The solution is to use a scroll view if you expect scrolling might be required.

I will close this and instead focus on the separate issue you opened on scroll view.

**Comment by qq759979949** [comment]
ok,thanks
