### ISSUE TITLE
BMScorllView can't go to editlayout page

### ISSUE THREAD

**Issue by qq759979949** [ptc-iot-sharing/BMCoreUIWidgets#22]
After I drag the BMScorllView into the mashup, when I click EditLayout, a window pops up and I don't get to the edit page. The Thingworx log shows the following “ERROR [widget] An error occurred while calling destroy for BMScrollViewWidget, Id = "BMScrollViewWidget-34". [{}]”
![Snipaste_2023-03-15_23-50-49](https://user-images.githubusercontent.com/35073724/225365711-f0c82167-dc7e-478d-bcec-82b904a6ae7a.png)

**Comment by BogdanMihaiciuc** [comment]
I will look into this.

**Comment by qq759979949** [comment]
by the way, I used it in thingworx 9.2 and 9.3, and both had this problem.

**Comment by BogdanMihaiciuc** [comment]
I will release a fix for this over the weekend. Thanks for reporting

**Comment by BogdanMihaiciuc** [comment]
This should be fixed by the 2.9.3 release. Please reopen if you are still having issues.
